In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
## your code
numbers = np.arange(1, 21)
result = (2 ** numbers) / numbers

In [3]:
result

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [4]:
## your code
i = np.arange(0, 6)
result_2 = (0.1 ** (3 * i) * 0.2 ** (4 * i)).sum()

In [5]:
result_2

1.00000160000256

**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [6]:
## your code
mtr = np.zeros((8, 8))
mtr[::2,  ::2], mtr[1::2, 1::2] = 1, 1

In [7]:
mtr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [8]:
X = np.random.random((5, 2))

In [9]:
x = X[:, 0]
y = X[:, 1]

radius = (x ** 2 + y ** 2) ** (1 / 2)
phi = np.arccos(x / radius)

polar_coordinate = ((radius, phi))

In [10]:
polar_coordinate

(array([1.26757823, 1.05226199, 0.5924557 , 0.73054796, 0.71614289]),
 array([0.82341192, 0.93853917, 0.18354741, 0.46616191, 1.38992297]))

**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [11]:
X = np.random.random((10, 10))
ind_max = np.unravel_index(np.argmax(X), X.shape)
## your code

In [12]:
ind_max

(8, 1)

**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [13]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

diff_x_y = X - y
first_coor = diff_x_y[:, 0].copy()
second_coor = diff_x_y[:, 1].copy()
sqrt_diff = (first_coor ** 2 + second_coor ** 2) ** (1 / 2)
near_point = np.argmin(sqrt_diff)

In [14]:
X[near_point]

array([0.04914051, 0.30135271])

**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [15]:
## your code
def function(x):
    if x < 0: 
        return x ** 2 + 2 * x + 6 
    elif x >=2 and x <=0: 
        return x + 6 
    else:
        return x ** 2 + 4 * x - 4

mass = np.arange(-3, 3.5, 0.5)
res = list(map(function, mass))

In [16]:
res

[9.0, 7.25, 6.0, 5.25, 5.0, 5.25, -4.0, -1.75, 1.0, 4.25, 8.0, 12.25, 17.0]

**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [17]:
## your code
X = np.random.random((10, 10))
X = X - X.mean(axis=1).reshape(10, 1)

In [18]:
X.mean(axis=1)

array([ 4.44089210e-17,  9.99200722e-17,  6.66133815e-17, -4.44089210e-17,
       -4.44089210e-17,  0.00000000e+00, -2.22044605e-17, -5.55111512e-17,
        6.66133815e-17,  0.00000000e+00])

**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [19]:
X = np.random.normal(loc=5, scale=2., size=1000)
print(X.mean(), X.var())

5.044842426474259 4.07295037560947


**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [20]:
## your code
x = np.arange(5)
res = (x + x.reshape(5, 1)) % 5

In [21]:
res

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [22]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
        print(cur)
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

50
0
54
61
0


[1, 0, 3, 4, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [23]:
## your code
from itertools import accumulate
def sample(x, c):
    assert len(x) > 0

    s = np.sum(x)
    val = (s * np.random.random(c)).reshape(-1, 1)
    cur_sum = list(accumulate(x))
    result = np.sum((cur_sum <= val), axis=1)
    return result

In [24]:
sample([50, 3, 1, 7, 20], 5) 

array([0, 0, 0, 0, 0])